services:
  - type: web
    name: multimodal-search
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python frontend/app.py"
    envVars:
      - key: PYTHONPATH
        value: .
      - key: KMP_DUPLICATE_LIB_OK
        value: "TRUE"
