services:
  - type: web
    name: multimodal-search
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python frontend/app.py"
    envVars:
      - key: PYTHONPATH
        value: .
      - key: KMP_DUPLICATE_LIB_OK
        value: "TRUE"
      - key: MALLOC_ARENA_MAX
        value: "2"
      - key: OMP_NUM_THREADS
        value: "1"
      - key: MKL_NUM_THREADS
        value: "1"
      - key: OPENBLAS_NUM_THREADS
        value: "1"
      - key: PYTHONMALLOC
        value: "malloc"
